server:
  port: 8080
  host: 0.0.0.0
  pool: 
    size: 100
  auth: 
    username: rust
    password: proxy
# 
deny:
  request:
    line: 
      methods: [POST, PUT]
      path: 
        - /login
    headers:
      - 
        key: "Content-Type"
        value: "application/json"
        
  response:
      headers:
      - 
          key: "Content-Type"
          value: "pdf"