name: Rust

on:
  push:
    branches: [ master ]
    paths:
      - "**.rs "
      - "**/Makefile"
      - "**/Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test
